### ISSUE TITLE
serveDirectory isn't working as expected.

### ISSUE THREAD

**Issue by arianvp** [haskell-servant/servant-server#1]
If I have a Raw entrypoint the directory is listed but navigating the directory isn't supported.

say I have

                                              
    type MyApi =  "static" :> Raw                                         
   
    myApi :: Proxy MyApi                                                
    myApi = Proxy                                                       
                                                                       
    server = serveDirectory "/home/arian/Projects/ghcjs-servant-client"   
    main = Network.Wai.Handler.Warp.run 3000 (serve myApi $ server) 

It will show the contents of the directory `/home/arian/Projects/ghcjs-servant-client`

but if I want to browse into a subdirectory or open a file in that directory  , say the file `/home/arian/Projects/ghcjs-servant-client/README`  instead of going to  `/static/README`  it goes to `/README` and returns a `404 not found`.

**Comment by alpmestan** [comment]
I've investigated this a bit.

We use the `wai-app-static` package to serve static files, with [`defaultFileServerSettings`](https://hackage.haskell.org/package/wai-app-static-3.0.0.5/docs/Network-Wai-Application-Static.html#g:2) (3rd entry in the section I've linked to).

One thing we do in `servant` conflicts with this: in your example, the wai app will not get "/static" as the request path, but just "/", so that we can blindly embed "external" WAI apps in webservices. The static file serving handler here doesn't know it's under "/static".

@soenkehahn Any elegant idea to solve this?

**Comment by soenkehahn** [comment]
Note that this seems to work when using urls that end in `/` for directories. So in your example accessing `localhost:3000/static/` should work as expected. It seems to be related to this: https://github.com/yesodweb/wai/issues/312, although the fix there doesn't help us. So I would consider this a bug in `wai-app-static`. I'll be looking into this further.

On a more general note: Personally I would think that a file serving function should by default *not* create file listings. But I'm curious to hear about your usecase, @arianvp. Is this just for development or for production?

**Comment by soenkehahn** [comment]
I could reproduce this with `UrlMap` from `wai-extra`: https://github.com/yesodweb/wai/issues/325. As I understand this we could work around this in `servant-server`, if this is urgent. But I would rather wait for a fix upstream.

**Comment by soenkehahn** [comment]
This is fixed upstream: https://github.com/yesodweb/wai/commit/000490af664818300a24868020ddcd8559fd0e72

**Comment by soenkehahn** [comment]
We could add a lower bound in the cabal file (`wai-app-static >= 3.0.0.6`). I'm not sure, do we want that?

**Comment by alpmestan** [comment]
The next release is going to be a breaking one anyway, we could do just that so that nobody will ever encounter this bug again :)
