### ISSUE TITLE
Get rid of Proxy

### ISSUE THREAD

**Issue by mietek** [haskell-servant/servant-server#15]
As I understand, `Proxy` is currently unwanted but necessary.  I’ll be happy to help look into ways of making it unnecessary in the future.

cc @alpmestan

**Comment by jkarni** [comment]
@mietek if you figure out a way of doing this, that'd be great, but I don't see how we could easily disambiguate the types without `Proxy`

**Comment by jkarni** [comment]
Closing since I myself can't see an approach to this, but if you come up with something that'd be very welcome, of course
