### ISSUE TITLE
Improve error response for failed JSON parse

### ISSUE THREAD

**Issue by paf31** [haskell-servant/servant-server#19]
For practical purposes, it would be very useful for me to get a readable error message in the response body if the request body fails to parse.

Would you accept a PR to modify the `InvalidBody` constructor to take an error string?

**Comment by jkarni** [comment]
@paf31 not having error messages is indeed bad, and making `InvalidBody` take a string sounds reasonable. I think some `aeson` messages aren't of the sort you'd like to present to end-users, though: `"Failed: 'satisfy'"` doesn't make much sense to anyone who isn't specifically writing attoparsec/aeson code (and even then not all that much). And I can't think of an easy way of distinguishing between the good messages and the bad. 

I still think this is a good idea, and you should feel free to go ahead; some bad error messages sometimes is probably better than no error messages at all. And https://github.com/bos/aeson/pull/220 should help, if/when it lands.

**Comment by paf31** [comment]
Maybe the solution is to just log the error for now. Is there any logging mechanism right now? I'll put together a PR so that we can discuss anyway.

**Comment by jkarni** [comment]
Done in #20
