### ISSUE TITLE
Wanted: set response headers in handlers

### ISSUE THREAD

**Issue by thsutton** [haskell-servant/servant-server#25]
It would be really nice if Servant allowed a handler to set arbitrary HTTP headers in the response without defining many (many!) custom alternatives to `Post`, `Get`, etc.

My immediate need is to set the ETag header for use in subsequent `PUT` requests. I can probably address this with a new type `SettingETag` in my API types and a `HasServer` instance which just, e.g., calculates a checksum of the JSON as it goes past but more general support would be great.

**Comment by jkarni** [comment]
What about using a combinator? I'm inclined to try to maintain the handlers web-unaware to the greatest extent possible, and keep all HTTP-related logic in the combinators

**Comment by alpmestan** [comment]
@jkarni would your suggested combinator just wrap around `Get`, `Post`, etc to insert a *response* header automatically?

**Comment by thsutton** [comment]
Something like `"greet" :> SuccessStatus 200 "OK" :> Get '[JSON] Example'

**Comment by alpmestan** [comment]
I'm not a big fan of having such "details" appear in the API type (the `SuccessStatus` example above), at least not in the standard servant package (as opposed to in some local combinator to your project or something like that). I do agree however that we want to offer a way to tweak headers in responses, in the same way that we provide access to request headers.

Any idea on a general approach to this would be appreciated, I'll think about it too.

**Comment by jkarni** [comment]
Done in #41
