### ISSUE TITLE
Make NoContent consistent

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant-server#28]
@tvh made the default HTTP code for the `()` type be 204 No Content for `PATCH` (and removed the `[]` body), which I think is a great idea. We should implement this for other methods. Any thoughts about whether to use `Typeable`/`cast` or `OverlappingInstances`?

For reference, this is the relevant PR : #24

**Comment by alpmestan** [comment]
FWIW, I'd ideally like to keep `OverlappingInstances` and `UndecidableInstances` out of our codebases *unless there's no sane alternative to achieve our goal*. So I'd go with the `cast` solution here.

**Comment by jkarni** [comment]
What exactly is the problem with `OverlappingInstances` in this case? I think @tvh also objected to it, but I still don't see the issue. I can't see how the usual problems with the extension can be said to apply here...

The problem I have with `cast` is that that's a `Typeable` constraint is necessary. With that alone, *returning GADT types becomes suddenly very very hard*.

**Comment by jkarni** [comment]
On a related note, should we also make it the case that returning a `Nothing` returns 204?

**Comment by jkarni** [comment]
Done in #33
