### ISSUE TITLE
Use `HTTP.Status.Types.Status` instead of `(Int, String)` for errors

### ISSUE THREAD

**Issue by davidsd** [haskell-servant/servant-server#37]
Might it be simpler/safer to return a `Status` instead of `(Int, String)` in the case of a handler error? That way, we could re-use already-defined statuses like `ok200` or `forbidden403`. If we want custom error messages, we could just use `mkStatus` on our own.

**Comment by jkarni** [comment]
I think from discussions on IRC it seems we all think `Left` of the `EitherT` needs a more general overhaul (currently you can return bodies or headers). One suggestion was just having it be a WAI `Response`, but I agree that if we keep status code and reason string, we should combine them into `Status`.

**Comment by alpmestan** [comment]
Yeah but sometimes people also want to give back a response body with the response. Does that mean we should put a `Status` and some response body with its content type in a data type and have this be the Left part of our Either? The more I see it, the more I want to nuke EitherT altogether...

**Comment by jkarni** [comment]
This issue was moved to haskell-servant/servant#43
