### ISSUE TITLE
`:<|>` tries subsequent `Raw`s even for bad requests

### ISSUE THREAD

**Issue by soenkehahn** [haskell-servant/servant-server#42]
@phunehehe and I came up with a test case for this: https://github.com/haskell-servant/servant-server/compare/badRequest-bug?expand=1

I'm not sure this is a bug or wanted behaviour though.

**Comment by jkarni** [comment]
Ouch, tricky one. My intuition is that the `Raw` endpoint should be tried (any non-complete match should try other endpoints), but if the `Raw` endpoint fails, `400` should be returned. We'd have to check whether the `Raw` endpoint returned `2XX` though (not impossible, just annoying).

**Comment by jkarni** [comment]
This issue was moved to haskell-servant/servant#41
