### ISSUE TITLE
servant-server-0.4.0 broken by API change in system-filepath

### ISSUE THREAD

**Issue by peti** [haskell-servant/servant-server#45]
According to http://hydra.cryp.to/build/863123/nixlog/1/raw, the build is broken as follows:

~~~~~~~~~~~~~
src/Servant/Utils/StaticFiles.hs:36:41:
    Couldn't match type ‘system-filepath-0.4.13.4:Filesystem.Path.Internal.FilePath’
                   with ‘[Char]’
    Expected type: FilePath
      Actual type: system-filepath-0.4.13.4:Filesystem.Path.Internal.FilePath
    In the first argument of ‘defaultFileServerSettings’, namely
      ‘(decodeString (documentRoot ++ "/"))’
    In the first argument of ‘staticApp’, namely
      ‘(defaultFileServerSettings (decodeString (documentRoot ++ "/")))’
~~~~~~~~~~~~~~

This issue is particularly unpleasant because this build failures also breaks the builds of all users of this package -- `language-puppet` in particular.

**Comment by peti** [comment]
Duh, this is a duplicate of https://github.com/haskell-servant/servant/issues/81. I'm sorry for reporting this twice.

I see that the fix is in Git already. Will there be a new Hackage release soon?

**Comment by alpmestan** [comment]
Yes. We're wrapping up a paper this week so probably this weekend (re. the Hackage release) I think, unless I manage to find some time to quickly wrap up a release with this fix + a couple of other patches sometimes this week.

**Comment by peti** [comment]
Those build errors are causing us a lot of trouble. I've removed the Servant packages from the NixOS distribution for the time being to mitigate the issue.
